version: "3"

services:
  ubuntu:
    build: docker/ubuntu
    container_name: ubuntu
    networks:
      - homelab
  kali-linux:
    build: docker/kali-linux
    container_name: kali-linux
    networks:
      - homelab

networks:
  homelab:
