version: "3"

services:
  ubuntu:
    build:
      context: Dockerfiles
      dockerfile: Dockerfile_ubuntu
    container_name: ubuntu
    networks:
      - homelab
  kali-linux:
    build:
      context: Dockerfiles
      dockerfile: Dockerfile_kali_linux
    container_name: kali-linux
    networks:
      - homelab

networks:
  homelab:
