version: "3"

services:
  ubuntu:
    build: docker/ubuntu
    container_name: ubuntu
    networks:
      - homelab
  kalilinux:
    build: docker/kalilinux
    container_name: kalilinux
    networks:
      - homelab

networks:
  homelab:
